Feature/oss 113 tabs
flagbase/flagbase pull request #342
Opened 2022-04-21 10:06 UTC by shaikhspeare

## Context

Tabs for managing and removing entities such as instances and workspaces.

## Changes

This PR introduces the following changes:
* Added tabs
* Revamped the UI

## Tasks

I've completed the following tasks:
- [x] Signed the Contributers License Agreement (CLA)
- [ ] Added/updated tests
- [ ] Added/updated docs

2022-04-21 10:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/flagbase/flagbase?pullRequest=342) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/flagbase/flagbase?pullRequest=342) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Ali<br/>:x: shaikhspeare<br/><hr/>**Ali** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/flagbase/flagbase?pullRequest=342) it.</sub>

2022-04-21 12:41 UTC, cjoy commented
Looks like the build, test and lint pipeline is failing. Is it broken in master?

2022-04-23 01:05 UTC, cjoy requested changes
Added a few comments - minor changes (should take less than 10mins to address)

2022-04-23 01:05 UTC, cjoy commented on ui/app/index.tsx
> +import React from 'react'
Are you using eslint? I think I added some linting config, which we should probably use for consistency

2022-04-23 01:05 UTC, cjoy commented on ui/app/lib/entity-store/entity-actions.ts
> +        type: "add",
Is this supposed to be add or remove?

2022-04-23 01:05 UTC, cjoy commented on ui/app/lib/entity-store/entity-actions.ts
> +        type: "add",
Oh nvm, I think I get it now

2022-04-23 01:05 UTC, cjoy commented on ui/app/pages/instances/instances.tsx
> +            .map((instance) => {
nit: we can use optional chaining
`instance?.key.includes(filter)`

2022-06-26 11:50 UTC, shaikhspeare commented on ui/app/context/project.tsx
> +export type Project = {
will add in future PR

2022-06-27 23:01 UTC, merged